// <auto-generated />
namespace JCPCars.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class v4_cardetails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v4_cardetails));
        
        string IMigrationMetadata.Id
        {
            get { return "202009231749225_v4_cardetails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
