// <auto-generated />
namespace JCPCars.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class cartv2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cartv2));
        
        string IMigrationMetadata.Id
        {
            get { return "202009012018253_cart.v2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
